version: '2'

volumes:
 vol-db-confluence:
 vol-db-jira:
 vol-db-bitbucket:
 vol-db-artifactory:




services:

 app-confluence:
  depends_on:
  - db-confluence
  links:
  - db-confluence:postgres_confluence
  volumes:
  - ./confluence/confluence.cfg.xml:/var/atlassian/confluence/confluence.cfg.xml:rw

 db-confluence:
  restart: always
  image: postgres:9.2
  ports:
  - "5420:5420"
  expose:
  - "5420"
  hostname: postgres_confluence
  environment:
  - DEBUG=false
  - DB_USER=confluence_user
  - DB_ROLE=confluence_user
  - DB_PASS=confluence_pswd
  - DB_NAME=confluence
  - DB_PORT=5420
  volumes:
  - vol-db-confluence:/var/lib/postgresql